// AGGREGATIN INHERITANCE METHOD
// IT KNOW HAS A RELATIONSHIP BETWEEN CLASSES
// AGGREGATION COMPOSITED ONE OR TWO CLASS WITHIN AS DATA MEMBER OR (ENTITIES OF A PARTICULAR CLASS)
// IT'S ANOTHER FORM OF INHERITANCE 

#include <iostream> // INTPUT / OUTPUT STREAM OBJECT
#include "class.h" // INCLUDING CLASS HEADER FILE

using std::cout; // FOR OUTPUT
using std::cin; // FOR INPUT
using std::endl; // FOR END OF LINE
using std::string; // FOR STRING

// HEADING OF THE MAIN () FUNCTOIN
int main (void) {
    // CREATING FIRST OBJECT EXPLICILTY CALLING
     First f = First ("Vikash",20,"7-7-2005"); // EXPLICITLY CALLING OBJECT CALLING
     
     // PASSED FIRST CLASS OBJCT WITHIN SECOND OBJECT AS
     // REFERENCE OF FIRST OBJECT AND INITIALIZE SECOND 
     // CLASS PRIVATE COMPOSITED CLASS ENTITY 

     Second s (3938,&f); // IMPLICITLY CALLING OBJECT

     // displaying output statment as result
     s.display ();
    return 0;
}