// CLASS DEFINITION SECTION 

// INCLUDE PREPROCESSOR DIRECTIVE INPUT/OUTPUT STREAM HEADER FILE 
#include <iostream>

// INCLUDE HEADER FILE OF THE CLASS DECLARATION
#include "Header.h"

// INTIALIZTION OF SETFUNCTION 
/* SET FUNCTION A VOID DATA TYPE FUNCTION THAT USED FOR ONLY SET VALUE NOT RETURN ANY VALUE*/
void Header::setValue (int val) {
   value = val; // ASSIGN FUNCTION ARGUMENT VAL VALUE WITH IN PRIVATE DATA MEMBER
};

// RETURN VALUE OF PRIVATE DATA MEMBER
int Header::getValue () {
  return value;
}; 

// OUTPUT STATEMENT AS RESULT
void Header::displayMessage () {
    std::cout << "User Enter Value : " << value << std::endl; // STANDARD OUTPUT STREAM OBJECT STATEMENT
};
// GET FUNCTION IS RETURN TYPE FUNCTION THAT RETURN PRVIATE DATA MEMBER VAL VALUE 